I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "game/distribute.rpy", line 952, in python
  File "game/distribute.rpy", line 348, in python
TypeError: argument of type 'NoneType' is not iterable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/tom/ab/renpy/renpy/bootstrap.py", line 265, in bootstrap
    renpy.main.main()
  File "/home/tom/ab/renpy/renpy/main.py", line 297, in main
    if not renpy.arguments.post_init():
  File "/home/tom/ab/renpy/renpy/arguments.py", line 230, in post_init
    return commands[command]()
  File "game/distribute.rpy", line 952, in distribute_command
    Distributor(p, destination=args.destination, reporter=TextReporter(), packages=packages, build_update=args.build_update, noarchive=args.no_archive, packagedest=args.packagedest)
  File "game/distribute.rpy", line 348, in __init__
    if (packages is None and not i['hidden']) or (name in packages):
TypeError: argument of type 'NoneType' is not iterable

Linux-3.11.0-12-generic-x86_64-with-debian-wheezy-sid
Ren'Py 6.16.0.377
Ren'Py Launcher 6.16.0.377
