I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 39, in script call
    call d_yes
  File "game/script.rpy", line 49, in script call
    call others
  File "game/script.rpy", line 54, in script
    if others:
  File "game/script.rpy", line 54, in <module>
    if others:
NameError: name 'others' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 39, in script call
    call d_yes
  File "game/script.rpy", line 49, in script call
    call others
  File "game/script.rpy", line 54, in script
    if others:
  File "D:\Short-Novel\renpy_engine\renpy\ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "D:\Short-Novel\renpy_engine\renpy\python.py", line 2039, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Short-Novel\renpy_engine\renpy\python.py", line 2032, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 54, in <module>
    if others:
NameError: name 'others' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.4.596
csg 1.0
Thu Oct 31 21:19:03 2019
