I'm sorry, but an uncaught exception occurred.

While loading the script.
ScriptError: Name (u'/home/tom/ab/renpy/renpy/common/000atl.rpy', 1355805686, 0) is defined twice: at renpy/common/000atl.rpy:7 and renpy/common/000atl.rpy:7.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/tom/ab/renpy/renpy/bootstrap.py", line 265, in bootstrap
    renpy.main.main()
  File "/home/tom/ab/renpy/renpy/main.py", line 226, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "/home/tom/ab/renpy/renpy/script.py", line 177, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "/home/tom/ab/renpy/renpy/script.py", line 436, in load_appropriate_file
    if self.load_file(dir, fn + compiled, initcode):
  File "/home/tom/ab/renpy/renpy/script.py", line 320, in load_file
    self.finish_load(stmts, initcode)
  File "/home/tom/ab/renpy/renpy/script.py", line 392, in finish_load
    node.filename, node.linenumber))
ScriptError: Name (u'/home/tom/ab/renpy/renpy/common/000atl.rpy', 1355805686, 0) is defined twice: at renpy/common/000atl.rpy:7 and renpy/common/000atl.rpy:7.

Linux-3.11.0-14-generic-x86_64-with-Ubuntu-13.10-saucy
Ren'Py 6.16.3.502
 
